### ISSUE TITLE
希望增加一个abs函数

### ISSUE THREAD

**Issue by wkshare** [open-falcon/judge#1]
如题。

另外，函数是否可以嵌套使用？

**Comment by UlricQin** [comment]
原始需求是什么？

**Comment by wkshare** [comment]
@UlricQin 希望告警的触发表达式更灵活一些。

比如流量波动超过10%，如果使用pdiff，则需要配置两条告警条件，>10%和<-10%。

abs(pdiff(#3))，希望可以这么使用。

**Comment by UlricQin** [comment]
这个我们应该不会去支持了，社区如果有人愿意做的话只能靠社区力量了。对于pdiff，你说的这个需求当时也考虑过，不过因为策略是可以克隆的，所以编写起来没有那么麻烦，后来就放弃了，毕竟函数嵌套不好搞
