### ISSUE TITLE
在策略告警中，父子告警模板需要支持覆盖

### ISSUE THREAD

**Issue by modeyang** [open-falcon/judge#10]
加入告警模板B继承于A，A模板上策略是  `metric=errorcode.counts all(#1)>100`, 而B模板上策略是 `metric=errorcode.counts  tags: error_code=1003009  all(#1)>200`, 在judge代码中由于没有进行子策略覆盖父策略逻辑，导致A模板上的策略被触发产生告警，然而这并不是我所希望的。希望利用贪婪匹配优先匹配最合适的策略，然后再匹配其次的策略。

**Comment by modeyang** [comment]
@laiwei  不知道有没有什么办法解决这种问题？

**Comment by laiwei** [comment]
这个我们先暂存一下吧，需要讨论下，到底哪种对用户的使用场景最合适。

原则上，你可以在B模块上，加两条策略来解决你的问题：

metric=errorcode.counts all（#1）>100000  ##用来覆盖父模板中对应的策略
metric=errorcode.counts tags: error_code=1003009 all（#1）>200 ##设定你想要的阈值
