### ISSUE TITLE
报警判断错误

### ISSUE THREAD

**Issue by wdystone** [open-falcon/judge#7]
Metric:df.bytes.free.percent Tags:fstype=NTFS,mount=C: all(#3): 5.14668<1 Note: Max:3, Current:1 Timestamp:2016-04-25 19:33:00
这个问题需要怎样排查

**Comment by itxx00** [comment]
你确认这条不是恢复信息？

**Comment by wdystone** [comment]
这条是报警邮件的内容。

**Comment by wdystone** [comment]
前面有个OK,是代表恢复了吗？

**Comment by itxx00** [comment]
@wdystone  是的，ok代表恢复
